// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieRecommendationApi.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MovieRecommendationApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250114031444_UpdateMovieId")]
    partial class UpdateMovieId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("IdentityUserRole<string>");
                });

            modelBuilder.Entity("MovieRecommendationApi.Models.BelongsToCollection", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("BackdropPath")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "backdrop_path");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("PosterPath")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "poster_path");

                    b.HasKey("Id");

                    b.ToTable("BelongsToCollections");

                    b.HasAnnotation("Relational:JsonPropertyName", "belongs_to_collection");
                });

            modelBuilder.Entity("MovieRecommendationApi.Models.Credit", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.HasKey("Id");

                    b.ToTable("Credits");

                    b.HasAnnotation("Relational:JsonPropertyName", "credits");
                });

            modelBuilder.Entity("MovieRecommendationApi.Models.FavoriteMovie", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("MovieId")
                        .HasColumnType("text");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.HasKey("UserId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("FavoriteMovies");

                    b.HasAnnotation("Relational:JsonPropertyName", "favorite_movies");
                });

            modelBuilder.Entity("MovieRecommendationApi.Models.Genre", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "_id");

                    b.Property<string>("MovieId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Genres");

                    b.HasAnnotation("Relational:JsonPropertyName", "genres");
                });

            modelBuilder.Entity("MovieRecommendationApi.Models.Movie", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "_id");

                    b.Property<bool>("Adult")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "adult");

                    b.Property<string>("BackdropPath")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "backdrop_path");

                    b.Property<int?>("BelongsToCollectionId")
                        .HasColumnType("integer");

                    b.Property<int>("Budget")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "budget");

                    b.Property<string[]>("Categories")
                        .HasColumnType("text[]")
                        .HasAnnotation("Relational:JsonPropertyName", "categories");

                    b.Property<int?>("CreditsId")
                        .HasColumnType("integer");

                    b.Property<string>("Homepage")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "homepage");

                    b.Property<string>("ImdbId")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "imdb_id");

                    b.Property<int?>("MovieCreditId")
                        .HasColumnType("integer");

                    b.Property<string[]>("OriginCountry")
                        .HasColumnType("text[]")
                        .HasAnnotation("Relational:JsonPropertyName", "origin_country");

                    b.Property<string>("OriginalLanguage")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "original_language");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "original_title");

                    b.Property<string>("Overview")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "overview");

                    b.Property<double>("Popularity")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "popularity");

                    b.Property<string>("PosterPath")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "poster_path");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "release_date");

                    b.Property<int>("Runtime")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "runtime");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<string>("Tagline")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "tagline");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "title");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "tmdb_id");

                    b.Property<bool>("Video")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "video");

                    b.Property<double>("VoteAverage")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "vote_average");

                    b.Property<int>("VoteCount")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "vote_count");

                    b.HasKey("Id");

                    b.HasIndex("BelongsToCollectionId");

                    b.HasIndex("CreditsId");

                    b.HasIndex("MovieCreditId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("MovieRecommendationApi.Models.MovieCast", b =>
                {
                    b.Property<string>("CastId")
                        .HasColumnType("text");

                    b.Property<string>("MovieId")
                        .HasColumnType("text");

                    b.HasKey("CastId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieCasts");

                    b.HasAnnotation("Relational:JsonPropertyName", "movie_casts");
                });

            modelBuilder.Entity("MovieRecommendationApi.Models.MovieCredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("MovieCredits");

                    b.HasAnnotation("Relational:JsonPropertyName", "movie_credits");
                });

            modelBuilder.Entity("MovieRecommendationApi.Models.Person", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "_id");

                    b.Property<bool>("Adult")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "adult");

                    b.Property<List<string>>("AlsoKnownAs")
                        .HasColumnType("text[]")
                        .HasAnnotation("Relational:JsonPropertyName", "also_known_as");

                    b.Property<string>("Biography")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "biography");

                    b.Property<string>("Birthday")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "birthday");

                    b.Property<int?>("CreditId")
                        .HasColumnType("integer");

                    b.Property<string>("Deathday")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "deathday");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "gender");

                    b.Property<string>("Homepage")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "homepage");

                    b.Property<string>("ImdbId")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "imdb_id");

                    b.Property<string>("KnownForDepartment")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "known_for_department");

                    b.Property<int?>("MovieCreditsId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "place_of_birth");

                    b.Property<double>("Popularity")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "popularity");

                    b.Property<string>("ProfilePath")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "profile_path");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "tmdb_id");

                    b.HasKey("Id");

                    b.HasIndex("CreditId");

                    b.HasIndex("MovieCreditsId");

                    b.ToTable("People");

                    b.HasAnnotation("Relational:JsonPropertyName", "cast");
                });

            modelBuilder.Entity("MovieRecommendationApi.Models.ProductionCompany", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("LogoPath")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "logo_path");

                    b.Property<string>("MovieId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("OriginCountry")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "origin_country");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("ProductionCompanies");

                    b.HasAnnotation("Relational:JsonPropertyName", "production_companies");
                });

            modelBuilder.Entity("MovieRecommendationApi.Models.ProductionCountry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IsoCode")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "iso_3166_1");

                    b.Property<string>("MovieId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("ProductionCountries");

                    b.HasAnnotation("Relational:JsonPropertyName", "production_countries");
                });

            modelBuilder.Entity("MovieRecommendationApi.Models.RatingList", b =>
                {
                    b.Property<string>("MovieId")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.HasKey("MovieId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("RatingLists");

                    b.HasAnnotation("Relational:JsonPropertyName", "rating_lists");
                });

            modelBuilder.Entity("MovieRecommendationApi.Models.Review", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "content");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<string>("MovieId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "updated_at");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "url");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasAnnotation("Relational:JsonPropertyName", "reviews");
                });

            modelBuilder.Entity("MovieRecommendationApi.Models.SimilarMovie", b =>
                {
                    b.Property<string>("MovieId")
                        .HasColumnType("text");

                    b.Property<string>("SimilarMovieId")
                        .HasColumnType("text");

                    b.HasKey("MovieId", "SimilarMovieId");

                    b.HasIndex("SimilarMovieId");

                    b.ToTable("SimilarMovies");
                });

            modelBuilder.Entity("MovieRecommendationApi.Models.SpokenLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EnglishName")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "english_name");

                    b.Property<string>("IsoCode")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "iso_639_1");

                    b.Property<string>("MovieId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("SpokenLanguages");

                    b.HasAnnotation("Relational:JsonPropertyName", "spoken_languages");
                });

            modelBuilder.Entity("MovieRecommendationApi.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MovieRecommendationApi.Models.Video", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "key");

                    b.Property<string>("MovieId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<bool>("Official")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "official");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "published_at");

                    b.Property<string>("Site")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "site");

                    b.Property<int>("Size")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "size");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Videos");

                    b.HasAnnotation("Relational:JsonPropertyName", "trailers");
                });

            modelBuilder.Entity("MovieRecommendationApi.Models.WatchMovie", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("MovieId")
                        .HasColumnType("text");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.HasKey("UserId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("WatchMovies");

                    b.HasAnnotation("Relational:JsonPropertyName", "watch_movies");
                });

            modelBuilder.Entity("MovieRecommendationApi.Models.FavoriteMovie", b =>
                {
                    b.HasOne("MovieRecommendationApi.Models.Movie", "Movie")
                        .WithMany("FavoriteMovies")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MovieRecommendationApi.Models.User", "User")
                        .WithMany("FavoriteMovies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieRecommendationApi.Models.Genre", b =>
                {
                    b.HasOne("MovieRecommendationApi.Models.Movie", null)
                        .WithMany("Genres")
                        .HasForeignKey("MovieId");
                });

            modelBuilder.Entity("MovieRecommendationApi.Models.Movie", b =>
                {
                    b.HasOne("MovieRecommendationApi.Models.BelongsToCollection", "BelongsToCollection")
                        .WithMany()
                        .HasForeignKey("BelongsToCollectionId");

                    b.HasOne("MovieRecommendationApi.Models.Credit", "Credits")
                        .WithMany()
                        .HasForeignKey("CreditsId");

                    b.HasOne("MovieRecommendationApi.Models.MovieCredit", null)
                        .WithMany("Cast")
                        .HasForeignKey("MovieCreditId");

                    b.Navigation("BelongsToCollection");

                    b.Navigation("Credits");
                });

            modelBuilder.Entity("MovieRecommendationApi.Models.MovieCast", b =>
                {
                    b.HasOne("MovieRecommendationApi.Models.Person", "Cast")
                        .WithMany("MovieCasts")
                        .HasForeignKey("CastId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MovieRecommendationApi.Models.Movie", "Movie")
                        .WithMany("MovieCasts")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cast");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieRecommendationApi.Models.Person", b =>
                {
                    b.HasOne("MovieRecommendationApi.Models.Credit", null)
                        .WithMany("Cast")
                        .HasForeignKey("CreditId");

                    b.HasOne("MovieRecommendationApi.Models.MovieCredit", "MovieCredits")
                        .WithMany()
                        .HasForeignKey("MovieCreditsId");

                    b.Navigation("MovieCredits");
                });

            modelBuilder.Entity("MovieRecommendationApi.Models.ProductionCompany", b =>
                {
                    b.HasOne("MovieRecommendationApi.Models.Movie", null)
                        .WithMany("ProductionCompanies")
                        .HasForeignKey("MovieId");
                });

            modelBuilder.Entity("MovieRecommendationApi.Models.ProductionCountry", b =>
                {
                    b.HasOne("MovieRecommendationApi.Models.Movie", null)
                        .WithMany("ProductionCountries")
                        .HasForeignKey("MovieId");
                });

            modelBuilder.Entity("MovieRecommendationApi.Models.RatingList", b =>
                {
                    b.HasOne("MovieRecommendationApi.Models.Movie", "Movie")
                        .WithMany("RatingLists")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MovieRecommendationApi.Models.User", "User")
                        .WithMany("RatingLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieRecommendationApi.Models.Review", b =>
                {
                    b.HasOne("MovieRecommendationApi.Models.Movie", "Movie")
                        .WithMany("Reviews")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MovieRecommendationApi.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieRecommendationApi.Models.SimilarMovie", b =>
                {
                    b.HasOne("MovieRecommendationApi.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovieRecommendationApi.Models.Movie", "SimilarMovieEntity")
                        .WithMany()
                        .HasForeignKey("SimilarMovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("SimilarMovieEntity");
                });

            modelBuilder.Entity("MovieRecommendationApi.Models.SpokenLanguage", b =>
                {
                    b.HasOne("MovieRecommendationApi.Models.Movie", null)
                        .WithMany("SpokenLanguages")
                        .HasForeignKey("MovieId");
                });

            modelBuilder.Entity("MovieRecommendationApi.Models.Video", b =>
                {
                    b.HasOne("MovieRecommendationApi.Models.Movie", "Movie")
                        .WithMany("Videos")
                        .HasForeignKey("MovieId");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieRecommendationApi.Models.WatchMovie", b =>
                {
                    b.HasOne("MovieRecommendationApi.Models.Movie", "Movie")
                        .WithMany("WatchMovies")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MovieRecommendationApi.Models.User", "User")
                        .WithMany("WatchMovies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieRecommendationApi.Models.Credit", b =>
                {
                    b.Navigation("Cast");
                });

            modelBuilder.Entity("MovieRecommendationApi.Models.Movie", b =>
                {
                    b.Navigation("FavoriteMovies");

                    b.Navigation("Genres");

                    b.Navigation("MovieCasts");

                    b.Navigation("ProductionCompanies");

                    b.Navigation("ProductionCountries");

                    b.Navigation("RatingLists");

                    b.Navigation("Reviews");

                    b.Navigation("SpokenLanguages");

                    b.Navigation("Videos");

                    b.Navigation("WatchMovies");
                });

            modelBuilder.Entity("MovieRecommendationApi.Models.MovieCredit", b =>
                {
                    b.Navigation("Cast");
                });

            modelBuilder.Entity("MovieRecommendationApi.Models.Person", b =>
                {
                    b.Navigation("MovieCasts");
                });

            modelBuilder.Entity("MovieRecommendationApi.Models.User", b =>
                {
                    b.Navigation("FavoriteMovies");

                    b.Navigation("RatingLists");

                    b.Navigation("Reviews");

                    b.Navigation("WatchMovies");
                });
#pragma warning restore 612, 618
        }
    }
}
